/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package First;


import java.awt.Dimension;
import java.io.File;
import java.io.FileFilter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lenovo
 */
public class Display extends javax.swing.JFrame {
     public static int count;
     MyClass mc = new MyClass();
    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        Seek.setPreferredSize(new Dimension(400, 20));
        Seek.setValue(0);
        Volume.setValue(0);
        VolLable.setText("Vol "+Volume.getValue()+"%");
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        List = new javax.swing.JScrollPane();
        MyPlayList = new javax.swing.JList<>();
        Play = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Prev = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        Shuffle = new javax.swing.JButton();
        Repeat = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        Seek = new javax.swing.JSlider();
        PlayList = new javax.swing.JButton();
        songName = new javax.swing.JLabel();
        Volume = new javax.swing.JSlider();
        VolLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Player");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        List.setViewportView(MyPlayList);

        getContentPane().add(List, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 470, 380));

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-play-50.png"))); // NOI18N
        Play.setToolTipText("PLAY");
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlayMouseReleased(evt);
            }
        });
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        getContentPane().add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 60, 60));

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-fast-forward-50.png"))); // NOI18N
        Next.setToolTipText("NEXT");
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 60, 60));

        Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-rewind-50.png"))); // NOI18N
        Prev.setToolTipText("PREV");
        getContentPane().add(Prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 60, 60));

        Stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-stop-50.png"))); // NOI18N
        Stop.setToolTipText("STOP");
        Stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StopMouseReleased(evt);
            }
        });
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });
        getContentPane().add(Stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 60, 60));

        Shuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-shuffle-50.png"))); // NOI18N
        Shuffle.setToolTipText("SHUFFLE");
        Shuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShuffleActionPerformed(evt);
            }
        });
        getContentPane().add(Shuffle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 60, 60));

        Repeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-repeat-50.png"))); // NOI18N
        Repeat.setToolTipText("REPEAT");
        Repeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RepeatMouseReleased(evt);
            }
        });
        getContentPane().add(Repeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, 60));

        Pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-pause-50.png"))); // NOI18N
        Pause.setToolTipText("PAUSE");
        Pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PauseMouseReleased(evt);
            }
        });
        getContentPane().add(Pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 60, 60));

        Seek.setMajorTickSpacing(100);
        Seek.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SeekStateChanged(evt);
            }
        });
        getContentPane().add(Seek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 410, -1));

        PlayList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-playlist-64.png"))); // NOI18N
        PlayList.setToolTipText("ADD");
        PlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayListActionPerformed(evt);
            }
        });
        getContentPane().add(PlayList, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 60, 60));

        songName.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        songName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(songName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 360, 30));

        Volume.setOrientation(javax.swing.JSlider.VERTICAL);
        Volume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                VolumeStateChanged(evt);
            }
        });
        getContentPane().add(Volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 150));
        getContentPane().add(VolLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/violin-1906127__340.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
       Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-pause-50.png")));
    }//GEN-LAST:event_PlayActionPerformed

    private void ShuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShuffleActionPerformed
        
    }//GEN-LAST:event_ShuffleActionPerformed

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopActionPerformed

    private void PlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayListActionPerformed
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter("Music Files","mp3","mpeg3");
        JFileChooser chooser = new JFileChooser("D:\\songs");
        chooser.addChoosableFileFilter(filefilter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            mc.Stop();
            File myFile = chooser.getSelectedFile();
            String song = myFile + "";
            String name = chooser.getSelectedFile().getName();
            songName.setText(name);
            mc.Play(song);
           
        }
    }//GEN-LAST:event_PlayListActionPerformed

    private void StopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopMouseReleased
       mc.Stop();
    }//GEN-LAST:event_StopMouseReleased

    private void PlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseReleased
        mc.Resume();
    }//GEN-LAST:event_PlayMouseReleased

    private void PauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PauseMouseReleased
        mc.Pause();
        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/First/icons8-play-50.png")));
    }//GEN-LAST:event_PauseMouseReleased

    private void RepeatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepeatMouseReleased
       switch(count)
       {
           case 0:
               count = 1;
               break;
           case 1:
               count = 0;
               break;
       }
    }//GEN-LAST:event_RepeatMouseReleased

    private void SeekStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SeekStateChanged
        
    }//GEN-LAST:event_SeekStateChanged

    private void VolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_VolumeStateChanged
        VolLable.setText("Vol "+Volume.getValue()+"%");
    }//GEN-LAST:event_VolumeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane List;
    private javax.swing.JList<String> MyPlayList;
    private javax.swing.JButton Next;
    private javax.swing.JButton Pause;
    private javax.swing.JButton Play;
    private javax.swing.JButton PlayList;
    private javax.swing.JButton Prev;
    private javax.swing.JButton Repeat;
    private javax.swing.JSlider Seek;
    private javax.swing.JButton Shuffle;
    private javax.swing.JButton Stop;
    private javax.swing.JLabel VolLable;
    public static javax.swing.JSlider Volume;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel songName;
    // End of variables declaration//GEN-END:variables
}
